### ISSUE TITLE
Thoughts of Questionable Value

### ISSUE THREAD

**Issue by wrobstory** [blaze/cachey#2]
Food for thought. Most of these are really "Pandas things" and not "Dask things", but I'm kind of riffing here.

**For a DataFrame, what if we cached**
* Factorized columns
* Sorted columns or sorted Indices
* [The group index](https://github.com/pydata/pandas/blob/0ed46a0786f226ada80cfc8bf8795ff715625025/pandas/core/groupby.py#L3798) of a GroupBy, as well as [the index arrays](https://github.com/pydata/pandas/blob/0ed46a0786f226ada80cfc8bf8795ff715625025/pandas/core/groupby.py#L3800) for any given set of labels/columns in a given GroupBy

**For a dask bag, what if we cached**
* All intermediates in any given series of folds, mappings, filters, etc. For example, if I perform a `bag.filter(lambda x: x > 2).map(lambda x: x + 1)`, dask can cache the filter and the map in case either is ever called again with that particular lambda. The following could be a *terrible* idea. Still riffing.: 
```
import inspect
import hashlib

m = hashlib.md5()
foo = lambda x: x > 2
stringified = inspect.getsource(foo)
m.update(stringified)
m.digest()
```
Now you have a checksum on that particular lambda function that you can use as a key for that calc on that bag. 

**For a Dask DataFrame, what if we cached**
* The same as the dask bag example, but for `apply` or `map`s on the DataFrame (which tend to be terrible expensive). Same hashing of the function they're using for the apply or map, then caching of the `apply`ed or `map`ed columns or the entire Frame.
* Aggregations

In general, I think there could be huge wins in essentially taking snapshots of a given series of computations on any given sequence or DataFrame, and being able to reconstruct those from caches of both intermediates and final results. 

This actually could actually provide some compelling data flows on the distributed side of dask. If any given computation node fails, you could dramatically decrease the time it takes to re-run a given sequence of computations if you had all of those intermediate steps cached along the way. So for any given branch of the graph, if you've finished 5 of the 6 pieces of computation and the node fails, either you can wait for the node to stand back up and just finish step 6, or you can shuffle the intermediate cached result from step 5 to another node and finish step 6. Moving that intermediate is going to be way less expensive that moving the whole data block. This does, of course, assume you get the data from the failed node into storage where a new node can access it. 

End of riff.

**Comment by wrobstory** [comment]
Also, this is similar to some of the ideas behind RDDs in Spark, though I am a little fuzzy on how they perform intermediate caching for any given series of transformations.

**Comment by mrocklin** [comment]
Cool thoughts.  Some very brief responses (more tomorrow?)

1.  The approach of `cachey` is to *cache everything* and let the scoring mechanism determine what is important.  Presumably this would pick out intermediate parts of reductions and such that are both expensive to compute and cheap to store.  We endeavor not to specifically pick out any particular operations though and instead desire to have a local and general policy that accomplishes the same result but with more generality
2.  I view resilience to worker failure as a somewhat different topic.  The growing approach within `dask.distributed` when a worker dies is to look at the data that we have in distributed memory at the moment, the tasks that we still have to do, and figure out what intermediates we're missing and add the necessary tasks back on to the queue.  I suppose that we could try to identify chokepoints in the graph that would serve as cheap checkpointing, but I hesitate to optimize too heavily for the worker failure case; I haven't yet found job recovery times be anyone's pain point.

In general I want to disambiguate the term "caching" as I mean it when discussing `cachey`.  Caching can mean many things and often means "explicitly store intermediate results."  This is not what `cachey` does.  Instead, `cachey` operates more like `lrucache` or `memcached` and performs opportunistic caching of everything that flows through the system, using heuristics to retain only the "good stuff."  We very intentionally want this to be dumb but cheap and universally applied.  We want to gain some performance without thinking hard about it..  This is a purely side-effect optimization.

With regards to dask I expect to integrate `cachey` at the scheduling layer, where all high-level knowledge of dataframes or bags is lost and we're just looking at python functions, runtimes, and byte costs.

**Comment by wrobstory** [comment]
```With regards to dask I expect to integrate cachey at the scheduling layer, where all high-level knowledge of dataframes or bags is lost and we're just looking at python functions, runtimes, and byte costs.```

Ahhhhh interesting, so you're implementing at the dict-as-graph layer? I'll be really interested in seeing how this plays out (hardest problems in computer science and all that), particularly with invalidation of caches downstream. In theory the structure of dask should make this *easier*, right? You already have a dependency graph, so invalidating caches means walking that tree again for anything downstream of upstream changes.

**Comment by mrocklin** [comment]
In dask we now key values based off of the keys in the dask graph.  I'm reconfiguring those keys now in https://github.com/ContinuumIO/dask/pull/510 (feedback welcome) to be more amenable (and safe) for long-term caching.

**Comment by mrocklin** [comment]
Looking through old issues and found this.  Update.  Dask.dataframe and dask.array both now use a consistent naming scheme that is amenable to caching.  There is a cache callback mechanism available as follows

```python
from dask.cache import Cache
cache = Cache(2e9) # 2GB
cache.register()
```

I've had good results from it as well as odd memory leaks on some machines.  I'd welcome others playing with it and providing feedback.

https://github.com/blaze/dask/blob/master/dask/cache.py

**Comment by wrobstory** [comment]
Awesome! Happy to close this for now.
